# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fcf862778eb07ea057f1d9f80c79e412931babd7ceeeca48b23cbca643cbe9607f45a576c3a569269bf20cd86b71e7cdc5867d1987c30f91b9713d4290de8cc7

test:
  secret_key_base: 57350d92b7948368bad1c0b407b25ea0b697146991021c72f1669a2423f0bd9b2511d29757c23027e083fe64e04c669aad62a194e5489b46138a4d95c9b3d587

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
